# Copyright (C) 2025 Maxim [maxirmx] Samsonov (www.sw.consulting)
# All rights reserved.
# This file is a part of Logibooks Core application

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: logibooks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: ./Logibooks.Core/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status/status"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 5s
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development

volumes:
  pgdata:
