// <auto-generated />
using System;
using Logibooks.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logibooks.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250711173117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logibooks.Core.Models.AltaException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("alta_exceptions");
                });

            modelBuilder.Entity("Logibooks.Core.Models.AltaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("alta_items");
                });

            modelBuilder.Entity("Logibooks.Core.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<short>("CountryIsoNumeric")
                        .HasColumnType("smallint")
                        .HasColumnName("country_iso_numeric");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inn");

                    b.Property<string>("Kpp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kpp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.HasKey("Id");

                    b.HasIndex("CountryIsoNumeric");

                    b.HasIndex("Inn")
                        .IsUnique();

                    b.ToTable("companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Москва",
                            CountryIsoNumeric = (short)643,
                            Inn = "7704217370",
                            Kpp = "997750001",
                            Name = "ООО \"Интернет Решения\"",
                            PostalCode = "123112",
                            ShortName = "",
                            Street = "Пресненская набережная д.10, пом.1, этаж 41, ком.6"
                        },
                        new
                        {
                            Id = 2,
                            City = "д. Коледино",
                            CountryIsoNumeric = (short)643,
                            Inn = "9714053621",
                            Kpp = "507401001",
                            Name = "",
                            PostalCode = "",
                            ShortName = "ООО \"РВБ\"",
                            Street = "Индустриальный Парк Коледино, д.6, стр.1"
                        });
                });

            modelBuilder.Entity("Logibooks.Core.Models.Country", b =>
                {
                    b.Property<short>("IsoNumeric")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("iso_numeric");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IsoNumeric"));

                    b.Property<string>("IsoAlpha2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iso_alpha2");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_at");

                    b.Property<string>("NameEnCldr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en_cldr");

                    b.Property<string>("NameEnFormal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en_formal");

                    b.Property<string>("NameEnOfficial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en_official");

                    b.Property<string>("NameEnShort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en_short");

                    b.Property<string>("NameRuFormal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ru_formal");

                    b.Property<string>("NameRuOfficial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ru_official");

                    b.Property<string>("NameRuShort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ru_short");

                    b.HasKey("IsoNumeric");

                    b.ToTable("countries");

                    b.HasData(
                        new
                        {
                            IsoNumeric = (short)643,
                            IsoAlpha2 = "RU",
                            LoadedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NameEnCldr = "Rusia",
                            NameEnFormal = "the Russian Federation",
                            NameEnOfficial = "Russian Federation",
                            NameEnShort = "Russian Federation (the)",
                            NameRuFormal = "Российская Федерация",
                            NameRuOfficial = "Российская Федерация",
                            NameRuShort = "Российская Федерация"
                        });
                });

            modelBuilder.Entity("Logibooks.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<string>("BoxNumber")
                        .HasColumnType("text")
                        .HasColumnName("box_number");

                    b.Property<string>("Brand")
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("CheckStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("check_status_id");

                    b.Property<string>("Composition")
                        .HasColumnType("text")
                        .HasColumnName("composition");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("CustomsClearance")
                        .HasColumnType("text")
                        .HasColumnName("customs_clearance");

                    b.Property<string>("Declaration")
                        .HasColumnType("text")
                        .HasColumnName("declaration");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DutyPayment")
                        .HasColumnType("text")
                        .HasColumnName("duty_payment");

                    b.Property<string>("ExtId")
                        .HasColumnType("text")
                        .HasColumnName("ext_id");

                    b.Property<string>("FabricType")
                        .HasColumnType("text")
                        .HasColumnName("fabric_type");

                    b.Property<string>("FactoryAddress")
                        .HasColumnType("text")
                        .HasColumnName("factory_address");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("HeelHeight")
                        .HasColumnType("text")
                        .HasColumnName("heel_height");

                    b.Property<string>("Insole")
                        .HasColumnType("text")
                        .HasColumnName("insole");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("Lining")
                        .HasColumnType("text")
                        .HasColumnName("lining");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<string>("OtherReason")
                        .HasColumnType("text")
                        .HasColumnName("other_reason");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("text")
                        .HasColumnName("passport_number");

                    b.Property<string>("PersonalData")
                        .HasColumnType("text")
                        .HasColumnName("personal_data");

                    b.Property<string>("Pinfl")
                        .HasColumnType("text")
                        .HasColumnName("pinfl");

                    b.Property<string>("ProductLink")
                        .HasColumnType("text")
                        .HasColumnName("product_link");

                    b.Property<string>("ProductName")
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("RecipientAddress")
                        .HasColumnType("text")
                        .HasColumnName("recipient_address");

                    b.Property<string>("RecipientInn")
                        .HasColumnType("text")
                        .HasColumnName("recipient_inn");

                    b.Property<string>("RecipientName")
                        .HasColumnType("text")
                        .HasColumnName("recipient_name");

                    b.Property<int>("RegisterId")
                        .HasColumnType("integer")
                        .HasColumnName("register_id");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("Shk")
                        .HasColumnType("text")
                        .HasColumnName("shk");

                    b.Property<string>("SiteArticle")
                        .HasColumnType("text")
                        .HasColumnName("site_article");

                    b.Property<string>("Size")
                        .HasColumnType("text")
                        .HasColumnName("size");

                    b.Property<string>("Sole")
                        .HasColumnType("text")
                        .HasColumnName("sole");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("Sticker")
                        .HasColumnType("text")
                        .HasColumnName("sticker");

                    b.Property<string>("StickerCode")
                        .HasColumnType("text")
                        .HasColumnName("sticker_code");

                    b.Property<string>("Subcategory")
                        .HasColumnType("text")
                        .HasColumnName("subcategory");

                    b.Property<string>("Supplier")
                        .HasColumnType("text")
                        .HasColumnName("supplier");

                    b.Property<string>("SupplierInn")
                        .HasColumnType("text")
                        .HasColumnName("supplier_inn");

                    b.Property<string>("TnVed")
                        .HasColumnType("text")
                        .HasColumnName("tn_ved");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("unit_price");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("CheckStatusId");

                    b.HasIndex("RegisterId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "TnVed" }, "IX_orders_tn_ved");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Logibooks.Core.Models.OrderCheckStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("check_statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Загружен"
                        },
                        new
                        {
                            Id = 101,
                            Title = "Проблема"
                        },
                        new
                        {
                            Id = 201,
                            Title = "Проверен"
                        });
                });

            modelBuilder.Entity("Logibooks.Core.Models.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Не известен"
                        });
                });

            modelBuilder.Entity("Logibooks.Core.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("DTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtime");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("registers");
                });

            modelBuilder.Entity("Logibooks.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "logist",
                            Title = "Логист"
                        },
                        new
                        {
                            Id = 2,
                            Name = "administrator",
                            Title = "Администратор"
                        });
                });

            modelBuilder.Entity("Logibooks.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patronymic");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "maxirmx@sw.consulting",
                            FirstName = "Maxim",
                            LastName = "Samsonov",
                            Password = "$2b$12$eOXzlwFzyGVERe0sNwFeJO5XnvwsjloUpL4o2AIQ8254RT88MnsDi",
                            Patronymic = ""
                        },
                        new
                        {
                            Id = 2,
                            Email = "director@global-tc.ru",
                            FirstName = "Эльдар",
                            LastName = "Сергутов",
                            Password = "$2a$11$KUvUbYg79OvDjq9xFKw1Ge4AYboMse4xduI.ZD54vp28zkb4DjWfK",
                            Patronymic = "Юрьевич"
                        },
                        new
                        {
                            Id = 3,
                            Email = "wild@global-tc.ru",
                            FirstName = "Полина",
                            LastName = "Баландина",
                            Password = "$2a$11$zA1ohkl1U6UGbkhUlNvtTexHkbQ7CtiFnHTSsBc4xz8a5BY8D9yDS",
                            Patronymic = "Анатольевна"
                        });
                });

            modelBuilder.Entity("Logibooks.Core.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Logibooks.Core.Models.Company", b =>
                {
                    b.HasOne("Logibooks.Core.Models.Country", "Country")
                        .WithMany("Companies")
                        .HasForeignKey("CountryIsoNumeric")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Logibooks.Core.Models.Order", b =>
                {
                    b.HasOne("Logibooks.Core.Models.OrderCheckStatus", "CheckStatus")
                        .WithMany("Orders")
                        .HasForeignKey("CheckStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Logibooks.Core.Models.Register", "Register")
                        .WithMany("Orders")
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Logibooks.Core.Models.OrderStatus", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckStatus");

                    b.Navigation("Register");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Logibooks.Core.Models.Register", b =>
                {
                    b.HasOne("Logibooks.Core.Models.Company", "Company")
                        .WithMany("Registers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Logibooks.Core.Models.UserRole", b =>
                {
                    b.HasOne("Logibooks.Core.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logibooks.Core.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Logibooks.Core.Models.Company", b =>
                {
                    b.Navigation("Registers");
                });

            modelBuilder.Entity("Logibooks.Core.Models.Country", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Logibooks.Core.Models.OrderCheckStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Logibooks.Core.Models.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Logibooks.Core.Models.Register", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Logibooks.Core.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Logibooks.Core.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
