# Copyright (C) 2025 Maxim [maxirmx] Samsonov (www.sw.consulting)
# All rights reserved.
# This file is a part of Logibooks Core application

name: publish

on:
  push:
    tags:     [ 'v*' ]
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

env:
  LANG: ru_RU.UTF-8
  LC_ALL: ru_RU.UTF-8

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/logibooks.core
          tags: |
            type=semver,pattern={{version}},enable=${{ contains(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ contains(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}},enable=${{ contains(github.ref, 'refs/tags/v') }}
            type=sha,enable=true
          labels: |
            org.opencontainers.image.vendor=sw.consulting
            org.opencontainers.image.title=Logibooks Core
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.description=Logibooks core container

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Logibooks.Core/Dockerfile
          push:  ${{ contains(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
